# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c24365af650bb4c4f1c45c2dd8bdbf8021c5d558eeef30184c03d3c81b2fe6d1e5498b4dfa00cf003715c2b7b8b1e99caeb8e65596672d1c274398fdd1b6f0d

test:
  secret_key_base: 916e2bcd70e8d78ab830dc665562b696ddca461bf12a942fbec08b46a897f3ed2b123cdc1830d0082aee2b45b299cb13bf2ab4e5894f65f639a440d1514201ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
