# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a10385a4f6c3c9542b294aaa26a719f155d73774b2256595c1c1c3e8a153f4a93072cc96d679b149b942851309d6b49230f492c469a73b52a6c1cf44f774e59

test:
  secret_key_base: 368af12ac9fa791665f37669df7fdde2098b412d01db0f5c33e5f809130b18548dac0778f3e6e9a2678eda00c88a970bc99f83b2a21f7171281aa1a257d0bdff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
